export const StaticData = {
    Meta_title:"BYREDO Official Site | Perfumes, Candles &amp; Body Care",
    Meta_description:"Shop Byredo’s Collection of Perfumes, Candles, Makeup, Leather And Body Care.Free shipping &amp; Free returns. Complimentary samples.",
    locator_breadcrumb:"Store Locator",
    FindLocationtext:"Enter a town or postcode",
    Usemylocation:"Use my location",
    Search:"Search",
    Brandname:"Byredo",
    miles:"miles",
    tempClosed:"Temporarily Closed",
    StoreDetailbtn:"View Store Detail",
    Storehighlight:"Store Highlights",
    Days:"Days",
    Hours:"Hours",
    Minutes:"Minutes",
    Seconds:"Seconds",
    FAQheading:"How can we help ?",
    getDirection:"Directions",
    AllRegion:"All Regions of",
    NearStoretext:"NEARBY LOCATIONS",
    AllLocationtext:"View All Location",
    PagenotFound:"404 - Page Not Found",
    cantfind_page:"We're really sorry, we can't find the page you're looking for",
    Youcouldtry:"You could try",
    Previuspage:"Going back to the previous page",
    homePage:"Going back to the homepage",
    StoreFinder:"Store Finder",
    FAQs:"FAQs",
    DownloadApp:"Download Our App",
    cookie:"cookies policy",
    Closed:"Closed",
    DayofWeek:"Day of the Week",
    Reopenmessage:"Message - The store is temporarily closed. It will reopen at",
    Address:"Address",
    Telephone:"Telephone",
    Holdiay:"Holdiday Hours",
    }